SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE T_USERS;




/* Create Tables */

CREATE TABLE T_USERS
(
	ID VARCHAR(32) NOT NULL COMMENT 'ユーザー識別子',
	LASTNAME VARCHAR(32) COMMENT '氏',
	FIRSTNAME VARCHAR(32) COMMENT '名',
	UPDATETIME TIMESTAMP COMMENT '更新日時',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ユーザー情報';



